version: "3.7"
services:
  rtl-server:
    #build: ./
    image: ghcr.io/lizenzfass78851/docker-rtl-tcp:latest
    container_name: rtl-tcp
    restart: always
    ports:
     - "1234:1234"
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
