name: Clean Docker Registry

on:
  schedule:
    - cron: '10 3 * * 0'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  clean_docker_registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        id: ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Purge all untagged images
        uses: minish144/delete-untagged-action@v2
        with:
          github-token: ${{ github.token }}
          package-name: ${{ env.REPO_NAME }}
