name: Clean Docker Registry

on:
  schedule:
    - cron: '10 3 * * 0'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  clean_docker_registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check owner type
        id: check_owner
        run: |
          curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
          https://api.github.com/users/${{ github.repository_owner }} \
          | jq -r '.type' | tr '[:upper:]' '[:lower:]' > owner_type.txt
          OWNER_TYPE=$(cat owner_type.txt) 
          echo "OWNER_TYPE=$OWNER_TYPE" >> $GITHUB_OUTPUT
          echo "Owner type is $OWNER_TYPE"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Login to GitHub Container Registry
        id: ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Delete all containers from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v4      
        with:
          token: ${{ github.token }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          untagged_only: true
          owner_type: ${{ steps.check_owner.outputs.OWNER_TYPE }}
