name: Clean Docker Registry

on:
  schedule:
    - cron: '10 3 * * 0'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  clean_docker_registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: delete

    steps:
      - name: Login to GitHub Container Registry
        id: ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Delete all containers from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3      
        with:
          token: ${{ github.token }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          untagged_only: true

